all=set(["John","Mary","Tina","Fiona","Claire","Eva","Ben","Bill","Bert"])
english=set(["John","Mary","Fiona","Claire","Ben","Bill"])
math=set(["Mary","Fiona","Claire","Eva","Ben"])
a=english&math
b=all-math
c=english&b
print("英文與數學都及格",a)
print("數學不及格",b)
print("英文及格且數學不及格",c)